// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXUMNV1D2sQ3sVSez5mOkXlDijlJztVuE',
    appId: '1:768920332603:web:ae2282ae50ca2eeac42f1e',
    messagingSenderId: '768920332603',
    projectId: 'smart-tailor-e237f',
    authDomain: 'smart-tailor-e237f.firebaseapp.com',
    storageBucket: 'smart-tailor-e237f.firebasestorage.app',
    measurementId: 'G-3Z9M3CSQ46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG63cOw2fgpZVrUPwKOxuRbzjS-UkQCQ8',
    appId: '1:768920332603:android:1735ae8ec29652dfc42f1e',
    messagingSenderId: '768920332603',
    projectId: 'smart-tailor-e237f',
    storageBucket: 'smart-tailor-e237f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZB9UjHaUMVodNh0iDP9j-o0Swtm_WgI',
    appId: '1:768920332603:ios:0e0d10af7fe4ea75c42f1e',
    messagingSenderId: '768920332603',
    projectId: 'smart-tailor-e237f',
    storageBucket: 'smart-tailor-e237f.firebasestorage.app',
    androidClientId: '768920332603-sk3r7fllp981tprf4pdnvvu3ng9ltknn.apps.googleusercontent.com',
    iosClientId: '768920332603-4j8utqrh4rqk2fs1diugrdv63417c7jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTailor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaZB9UjHaUMVodNh0iDP9j-o0Swtm_WgI',
    appId: '1:768920332603:ios:0e0d10af7fe4ea75c42f1e',
    messagingSenderId: '768920332603',
    projectId: 'smart-tailor-e237f',
    storageBucket: 'smart-tailor-e237f.firebasestorage.app',
    androidClientId: '768920332603-sk3r7fllp981tprf4pdnvvu3ng9ltknn.apps.googleusercontent.com',
    iosClientId: '768920332603-4j8utqrh4rqk2fs1diugrdv63417c7jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTailor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXUMNV1D2sQ3sVSez5mOkXlDijlJztVuE',
    appId: '1:768920332603:web:cf2e085fe526c0cbc42f1e',
    messagingSenderId: '768920332603',
    projectId: 'smart-tailor-e237f',
    authDomain: 'smart-tailor-e237f.firebaseapp.com',
    storageBucket: 'smart-tailor-e237f.firebasestorage.app',
    measurementId: 'G-0FY9V232T2',
  );

}